replicaCount: 1

image:
  repository: harbor.biluta.ru/office-memes/memes-front
  tag: dev-latest
  pullPolicy: Always

activeProfile: default

service:
  type: ClusterIP
  port: 80

ingress:
  path: /
  pathType: Prefix
  hosts:
    - mem.biluta.ru

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"